export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_WORK_SHIFTS = "GET_WORK_SHIFTS"
export const WORK_SHIFT_LOADING = "WORK_SHIFT_LOADING"